import {Injectable} from '@angular/core';
import {Router} from '@angular/router';
import {SessionService} from './session.service';
import {MessageService} from 'primeng/api';
import {AuthService} from './auth.service';

@Injectable({
    providedIn: 'root',
})
export class AuthDefaultService {
    public title: string = 'Home';

    constructor(
        private router: Router,
        private sessionService: SessionService,
        private messageService: MessageService,
        private authService: AuthService,
    ) {
    }

    async signOut(
        redirect: string,
        showSessionExpiredMessage: boolean = false,
        client_id: string | null = null,
    ): Promise<void> {
        if (showSessionExpiredMessage) {
            this.messageService.add({
                severity: 'warn',
                summary: 'Session Expired',
                detail: 'Your session has expired. Please log in again.',
                life: 5000,
            });
        }

        // Read the alias stored during the OAuth flow before clearing anything.
        // The JWT's client_id field is the internal UUID — using it in the next
        // authorize call makes isFirstParty=false and triggers the consent screen.
        const oauthClientAlias = window.sessionStorage.getItem('oauth-client-id');
        const refreshToken = this.sessionService.getRefreshToken();

        // Only call the logout API if we have a refresh token to revoke.
        // If the token was already cleared or never set, skip the server call
        // but still proceed with local cleanup and redirect.
        if (refreshToken) {
            // POST /api/oauth/logout:
            //   - revokes the refresh token family
            //   - invalidates the server-side login session (sid)
            //   - clears the sid cookie via Set-Cookie in the response
            // withCredentials is set on the request so the sid cookie is sent.
            // Fire-and-forget — local cleanup proceeds regardless of server errors.
            try {
                await this.authService.logout(refreshToken);
            } catch {
                // proceed with local cleanup
            }
        }

        this.sessionService.clearSession();

        // Use the alias in priority order:
        //   1. Explicitly passed client_id (callers that already know the alias)
        //   2. Alias stored in sessionStorage from the last OAuth flow
        //   3. Nothing — /login will show the client_id form
        const resolvedClientId = client_id || oauthClientAlias || null;
        await this.navToLogin(redirect, resolvedClientId);
    }

    /**
     * Navigate the browser to /login, preserving the requested return path and
     * (optionally) the client_id. The OAuth `state`, `nonce`, and PKCE challenge
     * are generated by LoginComponent when the user submits credentials — not here.
     * Sending them now would bind them to a different tab's flow and break CSRF validation.
     */
    public async navToLogin(
        redirect: string,
        client_id: string | null,
    ): Promise<void> {
        const queryParams: Record<string, string> = {redirect_uri: redirect};
        if (client_id) {
            queryParams['client_id'] = client_id;
        }
        await this.router.navigate(['login'], {queryParams});
    }

    resetTitle() {
        this.title = 'Home';
    }

    setTitle(title: string) {
        this.title = title;
    }
}
