name: Build, Test and Create Docker Image

on:
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        name: Run Unit & E2E Tests
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            # ---------- Docker buildx ----------
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Run Srv Test
                working-directory: srv
                run: |
                    npm ci            # Install exact dependencies based on package-lock.json
                    npm run release

            -   name: Run UI Test
                working-directory: ui
                run: |
                    npm ci            # Install exact dependencies based on package-lock.json
                    npm run build
                    npm run test -- --watch=false --browsers=ChromeHeadless
                    npm run e2e:test

    build-docker:
        name: Build Docker Images
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            # ---------- Docker buildx ----------
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            # ---------- Build docker images ----------
            -   name: Build srv Docker image
                run: |
                    cd srv
                    docker build -t auth-server-srv:latest .

            -   name: Build ui Docker image
                run: |
                    cd ui
                    docker build -t auth-server-ui:latest .
