name: Build and Test

on:
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        name: Run Unit & E2E Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            -   name: Run Srv Test
                working-directory: srv
                run: |
                    npm ci
                    npm run release

            -   name: Run UI Test
                working-directory: ui
                run: |
                    npm ci
                    npm run build
                    npm run test -- --watch=false --browsers=ChromeHeadless
                    npm run e2e:test

    build-docker:
        name: Build Docker Image
        runs-on: ubuntu-latest

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Build standalone Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: standalone.dockerfile
                    push: false
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
